### PR TITLE
fix: python3 bootstrap handler should be called only once

### LINKED ISSUE #56: For `vercel dev`, it said `HTTP Error 500: Internal Server Error` (python3)
**There is something wrong with `vercel dev` command in my Windows 10.**

- Vercel CLI 20.1.0 dev (beta)
- Win10 Professional 1909
- Python 3.8.5 x86_64
- Without using venv
- Workspace Tree:
``` tree
├─.vercel
│      project.json
│      README.txt
└─api
        date.py
```
(* The content of date.py is same as [this file](https://vercel.com/docs/serverless-functions/supported-languages#python) as follows.)

``` python3
# date.py
from http.server import BaseHTTPRequestHandler
from datetime import datetime

class handler(BaseHTTPRequestHandler):

  def do_GET(self):
    self.send_response(200)
    self.send_header('Content-type', 'text/plain')
    self.end_headers()
    self.wfile.write(str(datetime.now().strftime('%Y-%m-%d %H:%M:%S')).encode())
    return
```

I ran command `vercel dev`, then it said `urllib.error.HTTPError: HTTP Error 500: Internal Server Error` when it called `req = urllib.request.urlopen(url, data)` in line 31 in [bootstrap.py](https://github.com/vercel/fun/blob/master/src/runtimes/python/bootstrap.py).

After I add `print(url)` in [bootstrap.py](https://github.com/vercel/fun/blob/master/src/runtimes/python/bootstrap.py), line 31.
The logs showed:
> PS C:\Users\AT\Desktop\test_vercel_dev> vercel dev
> Vercel CLI 20.1.0 dev (beta) — https://vercel.com/feedback
> 
> Ready! Available at http://localhost:3000
> Building @vercel/python@latest:api/date.py
> Installing required dependencies...
> Built @vercel/python@latest:api/date.py [3s]
> using HTTP Handler
> using HTTP Handler
> http://127.0.0.1:13320/2018-06-01/runtime/invocation/next  (<======= print(url) output!!!)
> <class 'OSError'>
> http://127.0.0.1:13320/2018-06-01/runtime/invocation/b6544f1d-ec26-40f2-bb76-02f69451c86c/error  (<======= print(url) output!!!)
> http://127.0.0.1:13320/2018-06-01/runtime/invocation/next  (<======= print(url) output!!!)
> http://127.0.0.1:13320/2018-06-01/runtime/invocation/next  (<======= print(url) output!!!)
> TypeError: Object prototype may only be an Object or null: undefined
> at Function.setPrototypeOf (<anonymous>)
> at new LambdaError (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:7870:16)   
> at Lambda.<anonymous> (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:7990:27)
> at Generator.next (<anonymous>)
> at fulfilled (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:7898:58)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> Traceback (most recent call last):
> File "C:\Users\AT\AppData\Local\co.zeit.fun\Cache\runtimes\python\bootstrap.py", line 148, in <module>
> TypeError: Cannot read property 'resolve' of null
> at RuntimeServer.<anonymous> (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:8526:31)      
> at Generator.next (<anonymous>)
> at C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:8433:71
> at new Promise (<anonymous>)
> at module.exports.__webpack_modules__.58371.__awaiter (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:8429:12)
> at RuntimeServer.handleNextInvocation (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:8517:16)
> at RuntimeServer.<anonymous> (C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:8488:33)      
> at Generator.next (<anonymous>)
> at C:\Users\AT\AppData\Roaming\npm\node_modules\vercel\dist\index.js:8433:71
> at new Promise (<anonymous>)
> lambda_runtime_main()
> File "C:\Users\AT\AppData\Local\co.zeit.fun\Cache\runtimes\python\bootstrap.py", line 131, in lambda_runtime_main
> (event, context) = lambda_runtime_next_invocation()
> File "C:\Users\AT\AppData\Local\co.zeit.fun\Cache\runtimes\python\bootstrap.py", line 57, in lambda_runtime_next_invocation
> res = LambdaRequest('invocation/next')
> File "C:\Users\AT\AppData\Local\co.zeit.fun\Cache\runtimes\python\bootstrap.py", line 32, in __init__
> req = urllib.request.urlopen(url, data)    (<======= this line crashed!!!)
> File "C:\Users\AT\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
> return opener.open(url, data, timeout)
> File "C:\Users\AT\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
> response = meth(req, response)
> File "C:\Users\AT\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response     
> response = self.parent.error(
> File "C:\Users\AT\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
> return self._call_chain(*args)
> File "C:\Users\AT\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain       
> result = func(*args)
> File "C:\Users\AT\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default    raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 500: Internal Server Error

---

**In addition: I did the same thing in WSL(Ubuntu18.04) in this Windows PC, it works well.**

So maybe it could not reproduce in other PC.

### PR DESCRIPTION
**Pull request by stkevintan**
fix #56

### CODE REVIEW

**Comment by stkevintan** [comment]
Hi, @styfle, could you help review this simple fix please? I believe most of the Windows users are blocked by this bug, thanks!

**Review by styfle — APPROVED** [review]
Looks good, thanks!

The repo is a little out of date because vercel dev usually calls startDevServer() instead of using this repo.

**Comment by stkevintan** [comment]
> Looks good, thanks!
> 
> The repo is a little out of date because vercel dev usually calls startDevServer() instead of using this repo.

I see, but as I checked the current bit, python runtime hasn't implemented the `startDevServer` interface yet. perhaps I can contribute later on.

**Comment by styfle** [comment]
Something is wrong with CI 🤔 
I created another PR to investigate (#78)

**Pull request merged**
