### PR TITLE
feat: automatically publish to npm

### PR DESCRIPTION
**Pull request by cb1kenobi**
Adds a publish step after tests run.

### CODE REVIEW

**Review by styfle — CHANGES_REQUESTED** [review]
This is missing a few files.

Needs a release config and also would be good to validate the PR title with the additional workflow. Also the version could be 0.0.0 so no one gets confused about manually versioning.

https://github.com/vercel/satori/pull/350

**Comment by cb1kenobi** [comment]
Added the config and set the version to `0.0.0-development`.

**Review by styfle — APPROVED** [review]
Thanks!

Remember we need to add the gh secret to this repo

**Comment by cb1kenobi** [comment]
Secret has been added to repo.

**Pull request merged**
